SET hive.cli.print.header=true;
SET hive.cli.print.current.db=true;
SET mapreduce.framework.name=local;
SET hive.exec.mode.local.auto=true;
SET hive.fetch.task.conversion=more;
SELECT '__EVIDENCE_01_DATABASE_TABLES__' AS evidence_section;
SHOW DATABASES;
USE iphone_analytics;
SHOW TABLES;
SELECT '__EVIDENCE_02_SILVER_SCHEMA__' AS evidence_section;
DESCRIBE FORMATTED silver_sales;
SELECT '__EVIDENCE_03_FACT_SCHEMA__' AS evidence_section;
DESCRIBE FORMATTED fact_sales;
SELECT '__EVIDENCE_05_PARTITIONS__' AS evidence_section;
SHOW PARTITIONS silver_sales;
SHOW PARTITIONS fact_sales;
SELECT '__EVIDENCE_06_PRODUCT_REVENUE__' AS evidence_section;
SELECT p.product_name, SUM(f.total_amount) AS revenue FROM fact_sales f JOIN dim_product p ON f.product_id=p.product_id GROUP BY p.product_name ORDER BY revenue DESC;
SELECT '__EVIDENCE_07_STORE_REVENUE__' AS evidence_section;
SELECT s.store_name, SUM(f.total_amount) AS revenue FROM fact_sales f JOIN dim_store s ON f.store_id=s.store_id GROUP BY s.store_name ORDER BY revenue DESC;
SELECT '__EVIDENCE_08_ROW_COUNTS__' AS evidence_section;
SELECT COUNT(*) AS bronze_sales_count FROM bronze_sales;
SELECT COUNT(*) AS silver_sales_count FROM silver_sales;
SELECT COUNT(*) AS fact_sales_count FROM fact_sales;
SELECT '__EVIDENCE_09_SILVER_SAMPLE__' AS evidence_section;
SELECT * FROM silver_sales LIMIT 10;
SELECT '__EVIDENCE_10_FACT_SAMPLE__' AS evidence_section;
SELECT * FROM fact_sales LIMIT 10;
SELECT '__EVIDENCE_11_DAILY_MONTHLY_CUSTOMERS__' AS evidence_section;
SELECT date_key, SUM(quantity) AS units, SUM(total_amount) AS revenue FROM fact_sales GROUP BY date_key ORDER BY date_key;
SELECT d.year, d.month, SUM(f.total_amount) AS revenue FROM fact_sales f JOIN dim_date d ON f.date_key=d.date_key GROUP BY d.year,d.month;
SELECT c.customer_name, COUNT(*) AS purchases, SUM(f.quantity) AS units, SUM(f.total_amount) AS revenue FROM fact_sales f JOIN dim_customer c ON f.customer_id=c.customer_id GROUP BY c.customer_name ORDER BY revenue DESC;
