USE iphone_analytics;
SET hive.cli.print.header=true;
SET mapreduce.framework.name=local;
SET hive.exec.mode.local.auto=true;
SET hive.fetch.task.conversion=more;
SELECT '__EVIDENCE_09_SILVER_SAMPLE__' AS evidence_section;
SELECT * FROM silver_sales LIMIT 10;
SELECT '__EVIDENCE_10_FACT_SAMPLE__' AS evidence_section;
SELECT * FROM fact_sales LIMIT 10;
SELECT '__EVIDENCE_11_DAILY_MONTHLY_CUSTOMERS__' AS evidence_section;
SELECT date_key, SUM(quantity) AS units, SUM(total_amount) AS revenue FROM fact_sales GROUP BY date_key;
SELECT d.year, d.month, SUM(f.total_amount) AS revenue FROM fact_sales f JOIN dim_date d ON f.date_key=d.date_key GROUP BY d.year,d.month;
SELECT c.customer_name, COUNT(*) AS purchases, SUM(f.quantity) AS units, SUM(f.total_amount) AS revenue FROM fact_sales f JOIN dim_customer c ON f.customer_id=c.customer_id GROUP BY c.customer_name;
